[package]
name = "compound_prism_designer"
version = "0.0.4"
authors = ["Julia Tatz <tatz.j@husky.neu.edu>"]
edition = "2018"
include = ["/src/**/*", "/Cargo.toml", "/pyproject.toml", "/compound_prism_designer/*.py", "/design_config.toml", "/README.md"]

[lib]
name = "compound_prism_designer"
bench = false
crate-type = ["rlib", "cdylib"]

[dependencies]
derive_more = { git = "https://github.com/JelteF/derive_more.git" }
arrayvec = { version = "0.5.1", default-features = false }
quasirandom = "0.2.1"
libm = "0.1.4"
rand="0.7.2"
rand_xoshiro = "0.4.0"
ordered-float = "1.0.2"
once_cell = "1.2.0"
pyo3 = { version="0.8.1", features = ["extension-module"], optional = true }
numpy = { version="0.7.0", optional = true }
ndarray = { version="0.13.0", optional = true }

[dev-dependencies]
criterion = "0.3"
cpuprofiler = "0.0.3"

[features]
default = ["pyext"]
pyext = ["pyo3", "numpy", "ndarray"]

[[bench]]
name = "benchmark"
harness = false

[profile.release]
opt-level=3
lto=true

[profile.bench]
debug = true

[package.metadata.maturin]
requires-dist = ["numpy~=1.17", "matplotlib~=3.0"]
requires-python = ">=3.7"
