[package]
name = "compound-prism-designer"
version = "0.0.1"
authors = ["Julia Tatz <tatz.j@husky.neu.edu>"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

[lib]
bench = false
crate-type = ["rlib", "cdylib"]

[dependencies]
derive_more = { version = "0.15.0", features = ["no_std"]}
arrayvec = { version = "0.5.1", default-features = false, features = ["array-sizes-33-128"] }
quasirandom = "0.2.1"
libm = "0.1.4"

[build-dependencies]
cbindgen = "0.9.0"

[dev-dependencies]
rand="0.7.0"
rand_xoshiro = "0.3.1"
criterion = "0.3"
cpuprofiler = "0.0.3"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
opt-level=3
lto=true

[profile.bench]
debug = true
