# The unit of legth, such as cm or in, (Optional, default="mm")
length-unit = "mm"

# Genetic algorithm optimization properties
[optimizer]
iteration-count = 256
population-size = 128
offspring-size = 64
crossover-distribution-index = 4
mutation-distribution-index = 2
mutation-probability = 0.05
seed = 5382628
epsilons = [2.5, 0.02, 0.1]

# Compound prism design specification
[compound-prism]
# Max number of prisms to use in design
max-count = 6
# Max height of the prisms in [length-unit]
max-height = 25
# Width of the prisms in [length-unit]
width = 7
ar-coating = true

# Incoming gaussian beam properties
[gaussian-beam]
# 1/e^2 beam width in [length-unit]
width = 3.2
# Minimum & Maximum wavelength in [micrometers]
wavelength-range = [0.5, 0.82]

# Detector array properties
[detector-array]
bin-count = 32
bin-size = 0.8
linear-slope = 1
linear-intercept = 0.1
# Total length of array in [length-unit]
length = 32
# Maximum accepted incident angle in [degrees] (max=90)
max-incident-angle = 45
