[config]
default_to_workspace = false

[tasks.format]
dependencies = []
command = "cargo"
args = ["fmt"]

[tasks.kernel]
toolchain = "nightly"
command = "cargo"
args = [
    "rustc",
    "--bin=kernel",
    "--manifest-path=compound_prism_designer_kernel/Cargo.toml",
    "--release",
    "--target=nvptx64-nvidia-cuda.json",
    "-Z", "build-std=core",
    "-Z", "features=all",
    "--",
    "--emit=asm=src/kernel.ptx",
    "-Ccodegen-units=1",
    "-Clto",
    "-Cembed-bitcode=yes",
    "-Ctarget-cpu=sm_32",
    "-Ctarget-feature=+ptx60",
    "-Clinker=echo",
    "-Z", "no-link",
    "-Z", "mir-opt-level=3",
]

[tasks.verify-kernel]
dependencies = ["kernel"]
command = "ptxas"
args = ["-v", "-arch=sm_52", "src/kernel.ptx"]

[tasks.bench]
command = "cargo"
args = ["bench", "--features=cuda", "-p", "compound_prism_designer"]

[tasks.test]
command = "cargo"
args = ["test", "--workspace", "--exclude", "compound_prism_designer_kernel"]

[tasks.build-python]
command = "maturin"
args = [
    "build",
    "--release",
    "--no-sdist",
    "--manylinux=off",
    "--rustc-extra-args=-Ctarget-feature=+fma",
    "--cargo-extra-args=\"--features=pyext\""
]

[tasks.python-develop]
command = "maturin"
args = [
    "develop",
    "--release",
    "--rustc-extra-args=-Ctarget-feature=+fma -Ctarget-cpu=native",
    "--cargo-extra-args=\"--features=pyext\""
]

[tasks.flow-build]
dependencies = [
    "format",
    "kernel",
    "python",
]

[tasks.flow-develop]
dependencies = [
    "format",
    "kernel",
    "verify-kernel",
    "python-devlop",
]
