[config]
default_to_workspace = false

[tasks.check]
env = {RUSTFLAGS = "-Z macro-backtrace" }
command = "cargo"
args = ["check", "--all-features", "--all-targets"]

[tasks.format]
dependencies = []
command = "cargo"
args = ["fmt"]

[tasks.kernel]
toolchain = "nightly"
command = "cargo"
args = [
    "rustc",
    "--lib",
    "--manifest-path=compound_prism_designer_kernel/Cargo.toml",
    "--release",
    "--target=nvptx64-nvidia-cuda.json",
    "-Z", "build-std=core",
    "--",
    "-Cllvm-args=--nvptx-fma-level=2",
    "-Cllvm-args=--nvptx-prec-divf32=0",
    "-Cllvm-args=--nvptx-prec-sqrtf32=0",
    "-Cllvm-args=--nvptx-sched4reg",
    "-Cllvm-args=--mul-constant-optimization",
    "-Cllvm-args=--enable-local-reassign",
    # "-Cllvm-args=--enable-dse-memoryssa",
    "-Cllvm-args=--inline-threshold=1024",
    "--emit=asm=src/kernel.ptx,llvm-ir=kernel.ll",
    "-Cpasses=mem2reg sroa",
    "-Copt-level=3",
    # "-Cdebuginfo=2",
    "-Clto",
    "-Cembed-bitcode=yes",
    "-Ctarget-cpu=sm_32",
    "-Ctarget-feature=+ptx60",
    "-Clinker=echo",
    "-Z", "no-link",
    "-Z", "mir-opt-level=4",
    "-Z", "combine_cgu",
    "-Z", "mutable-noalias=yes",
    "-Z", "inline-mir=yes",
    "-Z", "new-llvm-pass-manager=yes",
    "-Z", "unsound-mir-opts=yes",
]

[tasks.verify-kernel]
dependencies = ["kernel"]
command = "ptxas"
args = ["-v", "-arch=sm_52", "src/kernel.ptx"]

[tasks.bench]
env = {RUSTFLAGS = "-Ctarget-feature=+fma -Ctarget-cpu=native" }
command = "cargo"
# args = ["criterion", "--features=cuda", "-p", "compound_prism_designer"]
args = ["criterion", "-p", "compound_prism_designer"]

[tasks.test]
command = "cargo"
args = ["test", "--workspace", "--exclude", "compound_prism_designer_kernel"]

[tasks.test-derive]
env = { RUST_BACKTRACE = "full" }
command = "cargo"
args = ["test", "--package", "derive-wrapped-from", "--lib", "--", "--nocapture"]

[tasks.build-python]
command = "maturin"
args = [
    "build",
    "--release",
    "--no-sdist",
    "--manylinux=off",
    "--rustc-extra-args=-Ctarget-feature=+fma",
    "--cargo-extra-args=\"--features=pyext\""
]

[tasks.python-develop]
command = "maturin"
args = [
    "develop",
    "--release",
    "--rustc-extra-args=-Ctarget-feature=+fma -Ctarget-cpu=native",
    "--cargo-extra-args=\"--features=pyext\""
]

[tasks.flow-build]
dependencies = [
    "format",
    "kernel",
    "build-python",
]

[tasks.flow-develop]
dependencies = [
    "format",
    "kernel",
    "verify-kernel",
    "python-develop",
]
