nglass = 2

[spectrometer]
max-height = 25
prism-width = 7
bin-count = 32
bin-size = 0.8
linear-slope = 1
linear-intercept = 0.1
detector-array-length = 32
max-incident-angle = 45
angle-is-rad = false
wavelength-range = [ 0.5, 0.82,]
# Gaussian Beam
beam-width = 3.2
# Fiber Beam
# fiber-core-radius = 0.050
# numerical-aperture = 0.32
ar-coated = true

[optimizer]
cpu-only = false
parallelize = false
optimize-size = true
optimize-deviation = false
